name: 'action-test'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and package
        run: pnpm run build && pnpm run package

      - name: Notify deployment start
        uses: ./
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          desc: 'Deploying environment X'
          env: '["envX"]'
          debug: true

      - name: Notify deployment deactivation
        uses: ./
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: '["envX"]'
          debug: true

      - name: Notify deployment delete
        uses: ./
        with:
          step: delete-env
          token: ${{ secrets.GH_PAT_TOKEN }}
          env: '["envX"]'
          debug: true

      - name: Notify deployment start (multiple)
        uses: ./
        id: deployment2
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          desc: 'Deploying environment C and environment D'
          env: '["envC", "envD"]'
          debug: true

      - name: Notify deployment finish
        uses: ./
        with:
          step: finish
          status: 'success'
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment2.outputs.deployment_id }}
          debug: true

      - name: Notify deployment start (single string)
        uses: ./
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          desc: 'Deploying environment Z'
          env: envZ
          debug: true

      - name: Notify deployment deactivation (single string)
        uses: ./
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: envZ
          debug: true

      - name: Notify get env
        uses: ./
        id: envs
        with:
          step: get-env
          token: ${{ secrets.GITHUB_TOKEN }}
          debug: true

      - name: Notify deployment deactivation (dynamic)
        uses: ./
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ steps.envs.outputs.env }}
          debug: true
